### ISSUE TITLE
Build Issue applying khalti sdk

### ISSUE THREAD

**Issue by sujanmt** [khalti/khalti-android#10]
java.lang.IncompatibleClassChangeError: Superclass rx.Observable of rx.subjects.Subject is declared final (declaration of 'rx.subjects.Subject' appears in /data/app/com.koklass.order-LGXhpHNLtt9lt3Q3J7CUQw==/base.apk:classes7.dex)
        at khalti.checkOut.d.<init>(Unknown Source:14)
        at khalti.checkOut.CheckOutActivity.onCreate(Unknown Source:110)
        at android.app.Activity.performCreate(Activity.java:7003)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by pranishres** [comment]
Hello ! which khalti sdk version are you using 😃

**Comment by sarbagyastha** [comment]
Closing because of no activity. Reopen if needed.
