### ISSUE TITLE
Class 'khalti.checkOut.CheckOutActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener

### ISSUE THREAD

**Issue by subashz** [khalti/khalti-android#14]
`  compileSdkVersion 29
    buildToolsVersion "29.0.1"
    defaultConfig {
        applicationId "com.thesunbi.nepmeds"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }`

**Gradle Dependencies**
`    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'com.google.android.material:material:1.1.0-alpha10'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
    implementation 'androidx.navigation:navigation-fragment:2.2.0-alpha02'
    implementation 'androidx.navigation:navigation-ui:2.2.0-alpha02'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.2.0-alpha02'
    implementation 'androidx.navigation:navigation-ui-ktx:2.2.0-alpha02'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0-alpha04'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha04'
    implementation ('com.khalti:khalti-android:1.2.8')`

**Gradle.properties**
`
    kotlin.code.style=official
    android.enableJetifier=true
    org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
    android.useAndroidX=true
    android.enableR8 = false
`

**Crash Log**
`2019-09-16 16:52:57.256 23024-23024/com.thesunbi.nepmeds E/InputEventReceiver: Exception dispatching input event.
2019-09-16 16:52:57.257 23024-23024/com.thesunbi.nepmeds E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-09-16 16:52:57.260 23024-23024/com.thesunbi.nepmeds E/MessageQueue-JNI: java.lang.IncompatibleClassChangeError: Class 'khalti.checkOut.CheckOutActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.thesunbi.nepmeds-Qdq0rC66qqCNuKcVsJ0AOg==/base.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:826)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1799)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1783)
        at com.google.android.material.tabs.TabLayout$TabLayoutOnPageChangeListener.onPageSelected(TabLayout.java:3256)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:12593)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3028)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:441)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3413)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
        at android.view.View.dispatchPointerEvent(View.java:12832)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5667)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5193)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4832)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4889)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7697)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7666)
    	at android.view.ViewRootImpl.enqueueInputE
2019-09-16 16:52:57.260 23024-23024/com.thesunbi.nepmeds D/AndroidRuntime: Shutting down VM
2019-09-16 14:56:56.586 20947-20947/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thesunbi.nepmeds, PID: 20947
    java.lang.IncompatibleClassChangeError: Class 'khalti.checkOut.CheckOutActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.thesunbi.nepmeds-0cPfwgSeIU9sRJVd4k6kBA==/base.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:826)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1799)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1783)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1746)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2139)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2327)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-16 16:52:57.263 23024-23024/com.thesunbi.nepmeds E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thesunbi.nepmeds, PID: 23024
    java.lang.IncompatibleClassChangeError: Class 'khalti.checkOut.CheckOutActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.thesunbi.nepmeds-Qdq0rC66qqCNuKcVsJ0AOg==/base.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:826)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1799)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1783)
        at com.google.android.material.tabs.TabLayout$TabLayoutOnPageChangeListener.onPageSelected(TabLayout.java:3256)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:12593)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3028)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:441)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3413)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
        at android.view.View.dispatchPointerEvent(View.java:12832)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5667)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5193)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4832)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4889)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7697)
2019-09-16 16:52:57.263 23024-23024/com.thesunbi.nepmeds E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7666)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7599)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-16 16:52:57.265 23024-23024/com.thesunbi.nepmeds E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thesunbi.nepmeds, PID: 23024
    java.lang.IncompatibleClassChangeError: Class 'khalti.checkOut.CheckOutActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.thesunbi.nepmeds-Qdq0rC66qqCNuKcVsJ0AOg==/base.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:826)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1799)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1783)
        at com.google.android.material.tabs.TabLayout$TabLayoutOnPageChangeListener.onPageSelected(TabLayout.java:3256)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:12593)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3028)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:441)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3413)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
        at android.view.View.dispatchPointerEvent(View.java:12832)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5667)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5193)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4832)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4889)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7697)
2019-09-16 16:52:57.266 23024-23024/com.thesunbi.nepmeds E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7666)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7599)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by subashz** [comment]
Ok, fixed by using the 1.0.0 version of material for now.
