### ISSUE TITLE
Crash after loading eBanking list

### ISSUE THREAD

**Issue by rakezbohara** [khalti/khalti-android#15]
After successful response from :  
https://khalti.com/api/bank/?has_ebanking=true&page=1&page_size=100 
app is crashing with following error log:

`    java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.rakezb.ecommerce-NmD1WUkxgDTpNe-lz0hGfg==/base.apk!classes3.dex)
        at khalti.checkOut.EBanking.helper.a.a(Unknown Source:122)
        at khalti.checkOut.EBanking.helper.a.onBindViewHolder(Unknown Source:2)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:142)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1556)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
        at android.view.View.layout(View.java:20865)`

I am using andoridX 1.0.2

**Comment by JoshanTandukar** [comment]
Same issue is also showing here as well.

**Comment by Manjish** [comment]
use picasso version 2.5.2 this will fix the issue

**Comment by Manjish** [comment]
> Same issue is also showing here as well.
use picasso version 2.5.2 this will fix the issue

**Comment by ishowrunes** [comment]
I am currently working on v2 of this project. This issue will be fixed once it is released

**Comment by ishowrunes** [comment]
In the meantime, I will create a hotfix for this issue

**Comment by rakezbohara** [comment]
@Ishwor-Shrestha  sure, waiting for hotfix

**Comment by ishowrunes** [comment]
I have merged the hotfix with both master and develop. The fix has been deployed to version 1.02.09. I have also updated the package from khalti to com.khalti, so you should update your imports and xml layouts.

[Changelog](https://github.com/khalti/khalti-sdk-android/blob/master/CHANGELOG.mdl)
