### ISSUE TITLE
Error while integrating in old projects with build updates

### ISSUE THREAD

**Issue by kapilmhr** [khalti/khalti-android#4]
> FATAL

 FATAL EXCEPTION: RxNewThreadScheduler-7
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
                                                                         at java.lang.Thread.run(Thread.java)
                                                                      Caused by: java.lang.NoSuchMethodError: No virtual method log(Ljava/lang/String;)V in class Lokhttp3/internal/Platform; or its super classes (declaration of 'okhttp3.internal.Platform' appears in /data/app/com.frantic.kicksal-2/base.apk:classes5.dex)
                                                                         at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:108)
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:157)
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
at okhttp3.RealCall.execute(RealCall.java:57)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
at rx.Subscriber.setProducer(Subscriber.java:211)
at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
at rx.Observable.unsafeSubscribe(Observable.java:8666)
at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) 
at java.util.concurrent.FutureTask.run(FutureTask.java) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
                                                                         at java.lang.Thread.run(Thread.java)

**Comment by sagarparajuli02** [comment]
I have Similar error.
Did you find any solution?
`Process: com.nepalidol.yatripaymentnew, PID: 16198
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.nepalidol.yatripaymentnew-1/split_lib_dependencies_apk.apk)
        at khalti.checkOut.CheckOutActivity.c(Unknown Source)
        at khalti.checkOut.d$1.a(Unknown Source)
        at khalti.checkOut.d$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
        at khalti.checkOut.b$1.a(Unknown Source)
        at khalti.checkOut.b$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
        at khalti.checkOut.api.a$1.a(Unknown Source)
        at khalti.checkOut.api.a$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

**Comment by abnormalbbk** [comment]
Could you please post your build.gradle content and also could you provide more details on this error?

**Comment by sujanmt** [comment]
java.lang.IncompatibleClassChangeError: Superclass rx.Observable of rx.subjects.Subject is declared final (declaration of 'rx.subjects.Subject' appears in /data/app/com.koklass.order-zntA8irfVzvt_dvEPEr9GQ==/base.apk:classes5.dex)
 @abnormalbbk could you please check this

**Comment by sujanmt** [comment]
java.lang.IncompatibleClassChangeError: Superclass rx.Observable of rx.subjects.Subject is declared final (declaration of 'rx.subjects.Subject' appears in /data/app/com.koklass.order-LGXhpHNLtt9lt3Q3J7CUQw==/base.apk:classes7.dex)
        at khalti.checkOut.d.<init>(Unknown Source:14)
        at khalti.checkOut.CheckOutActivity.onCreate(Unknown Source:110)
        at android.app.Activity.performCreate(Activity.java:7003)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

@abnormalbbk could you please review on this??
