### ISSUE TITLE
Khalti Android SDK

### ISSUE THREAD

**Issue by krixnaas** [khalti/khalti-android#6]
I have followed all the steps. 
Including Khalti SDK show the problem of carbonX and Shadow problem!

**Comment by ishowrunes** [comment]
Can you post the logcat error

**Comment by krixnaas** [comment]
08-01 16:06:37.722 3712-3712/android.com.testapp E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 52
08-01 16:06:40.372 3712-3712/android.com.testapp E/dalvikvm: Could not find class 'khalti.carbonX.a.a.k', referenced from method khalti.carbonX.a.a
08-01 16:06:40.372 3712-3712/android.com.testapp E/dalvikvm: Could not find class 'khalti.carbonX.a.a.j', referenced from method khalti.carbonX.a.a
08-01 16:06:40.552 3712-3712/android.com.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.VerifyError: khalti/carbonX/c/b
                                                                       at khalti.carbonX.widget.Button.getShadow(Unknown Source)
                                                                       at khalti.carbonX.widget.FrameLayout.drawChild(Unknown Source)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                       at khalti.carbonX.widget.FrameLayout.internalDispatchDraw(Unknown Source)
                                                                       at khalti.carbonX.widget.FrameLayout.dispatchDraw(Unknown Source)
                                                                       at android.view.View.getDisplayList(View.java:13236)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at khalti.carbonX.widget.FrameLayout.drawChild(Unknown Source)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                       at khalti.carbonX.widget.FrameLayout.internalDispatchDraw(Unknown Source)
                                                                       at khalti.carbonX.widget.FrameLayout.dispatchDraw(Unknown Source)
                                                                       at android.view.View.getDisplayList(View.java:13236)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
                                                                       at android.view.View.getDisplayList(View.java:13236)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.view.View.draw(View.java:14379)
                                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                       at android.view.View.getDisplayList(View.java:13241)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.view.View.draw(View.java:14379)
                                                                       at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:450)
                                                                       at android.view.View.getDisplayList(View.java:13241)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.view.View.getDisplayList(View.java:13236)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.view.View.getDisplayList(View.java:13236)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.View.draw(View.java:14089)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3120)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2957)
                                                                       at android.view.View.draw(View.java:14379)
                                                                       at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2236)
                                                                       at android.view.View.getDisplayList(View.java:13241)
                                                                       at android.view.View.getDisplayList(View.java:13283)
                                                                       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
                                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2478)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2302)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1934)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1050)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5750)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:561)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
                                                                       at android.os.Handler.handleCallback(Handler.java:730)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                   	at android.os.Looper.loop(Looper.j

**Comment by krixnaas** [comment]
?

**Comment by krixnaas** [comment]
..found out with the version problem. 
Khalti dependency doesn't support below 
API level 19 i.e. KitKat
am I right?

**Comment by abnormalbbk** [comment]
The minimum supported sdk version is 14 ICE_CREAM_SANDWICH.

**Comment by krixnaas** [comment]
..Then can you please, say what I am doing wrong with the above Log code!

**Comment by abnormalbbk** [comment]
Can you post the build.gradle file for your app and what version of android studio are you using?

**Comment by krixnaas** [comment]
tried with different package name just now and got the same error. 
using Android Studio 3.0.1
------------------------- build.gradle-----------------------------------


apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "ithinkso.com.useful"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:support-annotations:27.1.1'
    compile 'com.khalti:khalti-android:1.2.3'
}

**Comment by abnormalbbk** [comment]
Which device have you used for test?

**Comment by krixnaas** [comment]
MicroMax - Device with Android KitKat
