### ISSUE TITLE
App Crashes. Whats going on i hve no idea.

### ISSUE THREAD

**Issue by stharzun** [khalti/khalti-android#7]
i am getting following error while run my Project

 Process: com.impactit.demokhaltiintegration, PID: 16796
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.impactit.demokhaltiintegration-2/split_lib_dependencies_apk.apk)
        at khalti.checkOut.CheckOutActivity.c(Unknown Source)
        at khalti.checkOut.d$1.a(Unknown Source)
        at khalti.checkOut.d$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
        at khalti.checkOut.b$1.a(Unknown Source)
        at khalti.checkOut.b$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
        at khalti.checkOut.api.a$1.a(Unknown Source)
        at khalti.checkOut.api.a$1.onNext(Unknown Source)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
11-27 14:18:22.487 2924-2924/? E/Icon: Unable to load resource 0x00000000 from pkg=com.android.systemui
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.Resources.getValue(Resources.java:1369)
        at android.content.res.MiuiResources.getValue(MiuiResources.java:146)
        at android.content.res.Resources.getDrawable(Resources.java:822)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:313)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:269)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:377)
        at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:179)
        at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:136)
        at com.android.systemui.statusbar.StatusBarIconView.updateDarkMode(StatusBarIconView.java:271)
        at com.android.systemui.statusbar.phone.SimpleStatusBar.updateDarkMode(SimpleStatusBar.java:275)
        at com.android.systemui.statusbar.phone.PhoneStatusBar$42.run(PhoneStatusBar.java:3872)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)

for more detail please check my code if possible
https://github.com/stharzun/KhaltiDemo

**Comment by ishowrunes** [comment]
I am not able to recreate this issue. Will have to dig deeper.

**Comment by abnormalbbk** [comment]
@stharzun 
Comment the following dependencies for now and run the app.
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:design:28.0.0'
For now use the same support library version as provided by Khalti. We will soon roll out the fix in next version.

**Comment by stharzun** [comment]
@abnormalbbk  thanks for this solution. Its working for lower support library

**Comment by sawin0** [comment]
> @stharzun
> Comment the following dependencies for now and run the app.
> implementation 'com.android.support:appcompat-v7:28.0.0'
> implementation 'com.android.support:design:28.0.0'
> For now use the same support library version as provided by Khalti. We will soon roll out the fix in next version.

When will fix be released? I am also having same problem.
